name: Tests

on:
  schedule:
    - cron: "0 5 * * 0"
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install
        run: make install

      - name: Linter
        run: make lint

      - name: Tests & Coverage
        run: make test-with-coverage
